[package]
authors = ["123Duo3 <123duo3@gmail.com>", "Icemic <bingfeng.web@gmail.com>"]
description = "Universal CJK Layouting Implementation in Rust"
edition = "2024"
exclude = ["examples"]
license = "MPL-2.0"
name = "tiqian"
repository = "https://github.com/tiqian-cjk/tiqian-rs"
version = "0.1.0"

include = ["src/**/*", "resources/hyphenation/**/*", "Cargo.toml", "README.md", "LICENSE"]

[features]
collections-hashbrown = ["dep:hashbrown"]
collections-std = []
default = ["collections-hashbrown"]

[dependencies]
bytecount = {version = "0.6", features = ["runtime-dispatch-simd"]}
icu_properties = {version = "2.3", features = ["compiled_data"]}

hashbrown = {version = "0.17", optional = true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mimalloc = "0.1.47"

[dev-dependencies]
harfrust = "0.13"
pollster = "1.0"
read-fonts = "0.43"
skrifa = "0.46"
vello = "0.10.0"
winit = "0.30"
