[package]
description = "Universal CJK Layouting Implementation in Rust"
edition = "2024"
exclude = ["examples"]
license = "MPL-2.0"
name = "tiqian"
repository = "https://github.com/Icemic/tiqian-rs"
version = "0.1.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
unicode-general-category = "1.1.0"
unicode-properties = {version = "0.1.4", features = ["emoji"]}

[dev-dependencies]
glifo = "0.3"
harfrust = "0.13"
read-fonts = "0.43"
skrifa = "0.46"
softbuffer = "0.4.6"
vello_cpu = "0.2.0"
winit = "0.30"
