[package]
authors = ["123Duo3 <123duo3@gmail.com>", "Icemic <bingfeng.web@gmail.com>"]
description = "Universal CJK Layouting Implementation in Rust"
edition = "2024"
exclude = ["examples"]
license = "MPL-2.0"
name = "tiqian"
repository = "https://github.com/tiqian-cjk/tiqian-rs"
version = "0.1.0"

include = ["src/**/*", "resources/hyphenation/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
unicode-general-category = "1.1.0"
unicode-properties = {version = "0.1.4", features = ["emoji"]}

[dev-dependencies]
harfrust = "0.13"
pollster = "1.0"
read-fonts = "0.43"
skrifa = "0.46"
vello = "0.10.0"
winit = "0.30"
